name: Periodic Healthcheck

on:
  push:
    branches: 
     - main
  schedule:
    - cron: '0 * * * *'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: periodic health
        uses: jtalk/url-health-check-action@v2
        with:
          url: 'https://pokedex-2121.herokuapp.com/health'
